name: Generate Cloudflare WARP wireguard config for Xray

on:
  workflow_dispatch:
  schedule: 
    - cron:  '*/5 * * * *'

jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v3

    - name: Generate config
      run: ./warp-reg.sh
      shell: bash        

    - name: Add config.json to release branch
      run: |
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config user.name "github-actions[bot]"

        git fetch
        
        if git ls-remote --exit-code --heads origin release >/dev/null 2>&1; then
          echo "'release' branch exists on remote, switching to 'release' branch"
          git checkout release
        else
          echo "'release' branch does not exist on remote, creating and switching to 'release' branch"
          git checkout --orphan release
          git rm -rf .
        fi
        
        date >> /tmp/date.ini && date=$(sed "s# #_#g" /tmp/date.ini)
        mv config_new.json "config_$date.json"
        git add "config_$date.json"
        git commit -am "Updated at $date"
            
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: release
        force: true
